version: "3.8"

services:
  frontend:
    container_name: next-js
    build:
      context: ../frontend
      dockerfile: ../dev-config/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/usr/app
    networks:
      - strapi
  cms:
    container_name: strapi
    build:
      context: ../cms
      dockerfile: ../dev-config/Dockerfile.cms
    ports:
      - "1337:1337"
    volumes:
      - ../cms:/usr/app
      - /app/node_modules
    environment:
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_SSL: ${DATABASE_SSL}
    networks:
      - strapi
  db:
    container_name: db
    platform: linux/amd64 #for platform error on Apple M1 chips
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - strapi
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - strapi
networks:
  strapi:
volumes:
  db:
