FROM node:18-alpine

WORKDIR /opt/app
COPY package.json package-lock.json ./
RUN npm install -g node-gyp
RUN npm config set fetch-retry-maxtimeout 600000 -g && npm install
ENV PATH /opt/app/node_modules/.bin:$PATH

# WORKDIR /opt/app
# COPY package*.json ./
RUN npm ci

COPY . .

CMD ["npm", "run", "develop"]